name: Build and Release DLSS Swapper

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0, v1.1

permissions:
  contents: write  # Needed to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust if you want to force .NET 9 when it's available

      - name: Display .NET Info
        run: dotnet --info

      - name: Restore dependencies
        run: |
          if [ -f "global.json" ]; then
            echo "⚠️ Detected global.json - checking for required SDK version..."
            required_sdk=$(cat global.json | jq -r '.sdk.version')
            echo "Required SDK: $required_sdk"
          fi
          dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish -c Release -o ./publish

      - name: Package Artifacts
        run: |
          cd publish
          zip -r ../dlss-swapper-${{ github.ref_name || github.run_number }}.zip .
          cd ..

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dlss-swapper-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact (Manual Runs)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: dlss-swapper-build
          path: dlss-swapper-${{ github.run_number }}.zip
