name: Build and Release DLSS Swapper

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0, v2.0
  workflow_dispatch:  # Allows manual trigger from Actions tab

permissions:
  contents: write  # Needed to create releases

jobs:
  build:
    runs-on: windows-latest  # Must use Windows for Windows-targeted builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore -p:EnableWindowsTargeting=true

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore -p:EnableWindowsTargeting=true

      - name: Publish
        run: |
          dotnet publish -c Release -o ./publish -p:EnableWindowsTargeting=true

      - name: Set Artifact Name
        run: |
          if ($env:GITHUB_REF_TYPE -eq "tag") {
            echo "ARTIFACT_NAME=dlss-swapper-${env:GITHUB_REF_NAME}.zip" >> $env:GITHUB_ENV
          } else {
            echo "ARTIFACT_NAME=dlss-swapper-manual.zip" >> $env:GITHUB_ENV
          }
        shell: pwsh

      - name: Package Artifacts
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath ./${{ env.ARTIFACT_NAME }}

      - name: Conditional Release Creation
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARTIFACT_NAME }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Output
        if: github.ref_type != 'tag'
        run: |
          echo "Manual run detected — skipping release upload."
