name: Build and Release DLSS Swapper

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0, v2.1, etc.

permissions:
  contents: write  # Required to create a release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.0.102
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.102'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Package Artifacts
        run: |
          cd publish
          zip -r ../dlss-swapper-${{ github.ref_name || 'manual' }}.zip .
          cd ..

      - name: Create Release (for tag builds only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dlss-swapper-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact (for manual runs)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: dlss-swapper-build
          path: dlss-swapper-manual.zip
